### ISSUE TITLE
no  http  sample?

### ISSUE THREAD

**Issue by wjkhappy14** [richardbishop/LoadRunnerSamples#3]
how to test the website balance ?

**Comment by richardbishop** [comment]
Hi, 
I just saw this. Are you looking to test a load balancer?
If so I'd recommend nginx, HAProxy or Squid. They;re all open source, you should be able to get one up and running in front of your test application. Depending on how you configure the load balancers, you may need to simulate load from multiple IP addresses. You can do this with either multiple load generators or by using IP spoofing.
Good luck :-)
RB
